name: Build, Test, and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 3.1.x

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.x
      
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build
        run: |
          dotnet restore
          dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish NuGet Package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Responder/Phlank.Responder.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
